version: 1
formatters:
  simple:
    format: '[%(asctime)s] %(levelname)s: %(processName)s %(threadName)s %(name)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  '':
    level: DEBUG
    handlers: [console]
    propagate: True
root:
  level: DEBUG
  handlers: [console]
