[tool.black]
force-exclude = '''/(diffusion_original|lpw).py'''

[tool.isort]
profile = "black"
force_to_top = ".logging"
skip_glob = ["*/lpw.py"]

[tool.mypy]
# ignore_missing_imports = true
exclude = [
    "onnx_web.diffusers.lpw_stable_diffusion_onnx"
]

[[tool.mypy.overrides]]
module = [
"arpeggio",
    "basicsr.archs.rrdbnet_arch",
    "basicsr.utils.download_util",
    "basicsr.utils",
    "basicsr",
    "boto3",
    "codeformer",
    "codeformer.facelib.utils.misc",
    "codeformer.facelib.utils",
    "codeformer.facelib",
    "compel",
    "controlnet_aux",
    "cv2",
    "diffusers",
    "diffusers.configuration_utils",
    "diffusers.loaders",
    "diffusers.models.attention_processor",
    "diffusers.models.autoencoder_kl",
    "diffusers.models.cross_attention",
    "diffusers.models.embeddings",
    "diffusers.models.modeling_utils",
    "diffusers.models.unet_2d_blocks",
    "diffusers.models.vae",
    "diffusers.utils",
    "diffusers.pipelines.latent_diffusion.pipeline_latent_diffusion",
    "diffusers.pipelines.onnx_utils",
    "diffusers.pipelines.paint_by_example",
    "diffusers.pipelines.pipeline_utils",
    "diffusers.pipelines.stable_diffusion",
    "diffusers.pipelines.stable_diffusion.convert_from_ckpt",
    "diffusers.schedulers",
    "diffusers.utils.logging",
    "facexlib.utils",
    "facexlib",
    "gfpgan",
    "gi.repository",
    "huggingface_hub",
    "huggingface_hub.file_download",
    "huggingface_hub.utils.tqdm",
    "mediapipe",
    "onnxruntime",
    "onnxruntime.transformers.float16",
    "piexif",
    "piexif.helper",
    "realesrgan",
    "realesrgan.archs.srvgg_arch",
    "safetensors",
    "timm.models.layers",
    "transformers",
    "win10toast"
]
ignore_missing_imports = true